# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Coupons' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'SwiftyJSON', '~> 3.1'
  pod 'SVProgressHUD'
  pod 'M13BadgeView'
  pod 'MaryPopin'
  pod 'ENSwiftSideMenu', :git => 'https://github.com/evnaz/ENSwiftSideMenu.git', :tag => '0.1.3'

end
